openapi: '3.0.3'

info:
  version: 1.0.0
  title: OppdragsInfo API (sokos-nav-oppdrag)
  description: API-tjeneste for å hente og presentere oppdragsinformasjon tilknyttet person eller foretak
  contact:
    name: PO Utbetaling
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: oppdragsinfo
    description: Hovedinformasjon om oppdrag tilknyttet person eller foretak
  - name: oppdragsdetaljer
    description: Detaljert informasjon om oppdrag tilknyttet person eller foretak
  - name: oppdragsdetaljertillegg
    description: Tilleggsopplysninger til oppdrag tilknyttet person eller foretak
  - name: oppdragslinje
    description: Linjeinformasjon til oppdrag tilknyttet person eller foretak

paths:
  /api/v1/oppdragsinfo/oppdrag:
    post:
      tags:
        - oppdragsinfo
      summary: Henter oppdragsdata tilknyttet person eller foretak
      description: Oppdragsopplysninger kan begrenses til faggruppekode, fagsystemId og vedtaksdato
      operationId: oppdrag

      requestBody:
        description: gjelderId som skal søkes på
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OppdragsInfoRequest'
        required: true

      responses:
        200:
          description: OK - Hvis oppdrag ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppdragsInfo'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

      security:
        - Bearer: [ ]

components:
  schemas:

    OppdragsInfoRequest:
      type: object
      required:
        - gjelderId
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
        faggruppeKode:
          type: string
          description: filtrering på faggruppeKode
    OppdragsInfo:
      type: object
      properties:
        gjelderId:
          type: string
        gjelderNavn:
          type: string
        harOmposteringer:
          type: boolean
        oppdragsListe:
          type: array
          items:
            $ref: '#/components/schemas/Oppdrag'

    Oppdrag:
      type: object
      properties:
        fagsystemId:
          type: string
        oppdragsId:
          type: integer
        navnFagGruppe:
          type: string
        navnFagOmraade:
          type: string
        kjorIdag:
          type: string
        typeBilag:
          type: string
        kodeStatus:
          type: string

    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Error type
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Error message, invalid value
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/oppdragsinfo/hentOppdrag
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header